const textSummaries = {
    "tune-tracer": `<h1>Tune Tracer</h1> is a mobile app developed for my Senior Capstone at Wayne State University. Our client wanted a tool similar to Shazam—that could <b>analyze a short audio recording and identify its musical mode</b>, specifically within the context of Arabic music traditions. I worked on a team of five students, where I served as <em>Team Leader and Machine Learning Lead</em>.<br><br>
    We used <b>Flutter</b> (a UI toolkit by Google) and <b>Dart</b> to design the app, which allowed us to build one interface that worked across both Android and iOS. On the backend, I led the development of a <b>machine learning model</b> in Python using tools like <b>TensorFlow, Keras</b> and a musical analysis library called <b>Librosa</b>. During our research, we found that speech recognition techniques could also be used to identify musical patterns. Building on this idea, I adapted an open-source model to recognize maqamat, an Arabic musical system used in storytelling and prayer.<br><br>
    Since the app couldn’t handle raw audio processing directly, I also built a <b>Flask API</b> to do the heavy lifting. The app sends the recording to a server, which formats the audio data before sending it back to the app for prediction. Despite the gray hairs and sleepless nights my senior project was overall a super positive experience. At the beginning of the semester I was really doubting myself so now it feels good to be able to look back and see that we actually did it, and did it well.`,
    "undergrad": `<h1>Neural Radiance Fields (NeRF)</h1> is a machine learning technique that reconstructs 3D scenes from a collection of 2D photographs. It works by analyzing a series of images taken from different angles around the subject. Then using the data to learn how light should behave at each point in space it generates new views of the scene, including angles that were never originally photographed.<br><br>
    This algorithm was the focus of my <em>undergraduate resesrch project</em> during my junior year at Wayne State University. My goal was to <b>understand the underlying math and architecture</b> of NeRF, <b>document how to use the algorithm and the conditions to create the best result</b>, and <b>explore potential practical applications in 3D modeling and computer vision</b>. I translated these findings into both a research paper and a slide presentation that would be approachable for audiences without a background in computer science or AI.<br><br>
    Because NeRF relies on a lot of low-level math and technical concepts, I spent a lot of time reading other papers and <b>teaching myself the fundamentals</b> just to make sense of how it all worked. Running experiments with the model was also challenging since it takes hour and hours to train, and most of my first results were disappointing—if they came out at all. But even those failed attempts helped me understand what to improve the next time. I feel that this particular project <b>really highlights what I love most about programming</b>. I love solving puzzles and riddles and working backwards though this documentation and code felt kind of like a big mystery where I try to figure out how a computer could possibly make this stuff happen. Feeling things click as I go from reading about them to seeing them in action was so satisfing and it <b>gave me the confidence to delve deeper into these intricate concepts.`,
    "room-raiser": `<h1>Room Raiser</h1> was the project I worked on for my senior year Software Engineering course. My team's idea was to create a application that would allow users to draft floorplans in 2D and view a 3D model of their drawing.<br><br> 
    I was responsible for creating the <em>drawing interface, which included the drafting grid, measurement tools, and snapping logic for precise lines.</em> I started with a Python prototype using the Tkinter UI library to test grid-snapping and drawing behavior, then rebuilt the system in <b>JavaScript</b> with test cases using <b>Mocha</b> once we decided to go with a web app.<br><br>
    The hardest part was definitelly figuring out how to implement the 3D generation within the contraints of the deadline and our abilities. I was able to find an <a href=https://github.com/grebtsew/FloorplanToBlender3d> open-source Blender plug-in</a> that would do exactly what we needed. To be able to ship all of the app components together, I combined the Floorplan-To-Blender repository, the Blender app itself, and our web app into a <b>Docker container</b> to easily deploy the pipeline.<br><br>
    This was my first foray into what the "professional software development process" might look like, and at times it was honestly <b>trial-by-fire</b>. The chaos of 5 developers with different ideas and schedules working on the same project at the same time was a huge hill to get over at first, but it became a lot easier as we <b>learned how best to communicate and plan (and struggle) together.`
};

export default textSummaries